//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://Services/", ConfigurationName="Service")]
public interface Service
{
    
    // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/registerRequest", ReplyAction="http://Services/Service/registerResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    registerResponse register(registerRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/registerRequest", ReplyAction="http://Services/Service/registerResponse")]
    System.Threading.Tasks.Task<registerResponse> registerAsync(registerRequest request);
    
    // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/moveFileRequest", ReplyAction="http://Services/Service/moveFileResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    moveFileResponse moveFile(moveFileRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/moveFileRequest", ReplyAction="http://Services/Service/moveFileResponse")]
    System.Threading.Tasks.Task<moveFileResponse> moveFileAsync(moveFileRequest request);
    
    // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/deleteFolderRequest", ReplyAction="http://Services/Service/deleteFolderResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    deleteFolderResponse deleteFolder(deleteFolderRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/deleteFolderRequest", ReplyAction="http://Services/Service/deleteFolderResponse")]
    System.Threading.Tasks.Task<deleteFolderResponse> deleteFolderAsync(deleteFolderRequest request);
    
    // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/uploadFileRequest", ReplyAction="http://Services/Service/uploadFileResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    uploadFileResponse uploadFile(uploadFileRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/uploadFileRequest", ReplyAction="http://Services/Service/uploadFileResponse")]
    System.Threading.Tasks.Task<uploadFileResponse> uploadFileAsync(uploadFileRequest request);
    
    // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/deleteFileRequest", ReplyAction="http://Services/Service/deleteFileResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    deleteFileResponse deleteFile(deleteFileRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/deleteFileRequest", ReplyAction="http://Services/Service/deleteFileResponse")]
    System.Threading.Tasks.Task<deleteFileResponse> deleteFileAsync(deleteFileRequest request);
    
    // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/seeStorageTreeRequest", ReplyAction="http://Services/Service/seeStorageTreeResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    seeStorageTreeResponse seeStorageTree(seeStorageTreeRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/seeStorageTreeRequest", ReplyAction="http://Services/Service/seeStorageTreeResponse")]
    System.Threading.Tasks.Task<seeStorageTreeResponse> seeStorageTreeAsync(seeStorageTreeRequest request);
    
    // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/downloadFileRequest", ReplyAction="http://Services/Service/downloadFileResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    downloadFileResponse downloadFile(downloadFileRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/downloadFileRequest", ReplyAction="http://Services/Service/downloadFileResponse")]
    System.Threading.Tasks.Task<downloadFileResponse> downloadFileAsync(downloadFileRequest request);
    
    // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/shareFileRequest", ReplyAction="http://Services/Service/shareFileResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    shareFileResponse shareFile(shareFileRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/shareFileRequest", ReplyAction="http://Services/Service/shareFileResponse")]
    System.Threading.Tasks.Task<shareFileResponse> shareFileAsync(shareFileRequest request);
    
    // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/stopSharingFileRequest", ReplyAction="http://Services/Service/stopSharingFileResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    stopSharingFileResponse stopSharingFile(stopSharingFileRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/stopSharingFileRequest", ReplyAction="http://Services/Service/stopSharingFileResponse")]
    System.Threading.Tasks.Task<stopSharingFileResponse> stopSharingFileAsync(stopSharingFileRequest request);
    
    // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/loginRequest", ReplyAction="http://Services/Service/loginResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    loginResponse login(loginRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/loginRequest", ReplyAction="http://Services/Service/loginResponse")]
    System.Threading.Tasks.Task<loginResponse> loginAsync(loginRequest request);
    
    // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/createFolderRequest", ReplyAction="http://Services/Service/createFolderResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    createFolderResponse createFolder(createFolderRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/createFolderRequest", ReplyAction="http://Services/Service/createFolderResponse")]
    System.Threading.Tasks.Task<createFolderResponse> createFolderAsync(createFolderRequest request);
    
    // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/verifySessionRequest", ReplyAction="http://Services/Service/verifySessionResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    verifySessionResponse verifySession(verifySessionRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/verifySessionRequest", ReplyAction="http://Services/Service/verifySessionResponse")]
    System.Threading.Tasks.Task<verifySessionResponse> verifySessionAsync(verifySessionRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services/")]
public partial class user
{
    
    private int idField;
    
    private string nameField;
    
    private string surnameField;
    
    private string emailField;
    
    private string passwordField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public int id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string surname
    {
        get
        {
            return this.surnameField;
        }
        set
        {
            this.surnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string email
    {
        get
        {
            return this.emailField;
        }
        set
        {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string password
    {
        get
        {
            return this.passwordField;
        }
        set
        {
            this.passwordField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services/")]
public partial class file
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services/")]
public partial class folder
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services/")]
public partial class response
{
    
    private int statusCodeField;
    
    private string detailsField;
    
    private string jsonField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public int statusCode
    {
        get
        {
            return this.statusCodeField;
        }
        set
        {
            this.statusCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string details
    {
        get
        {
            return this.detailsField;
        }
        set
        {
            this.detailsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string json
    {
        get
        {
            return this.jsonField;
        }
        set
        {
            this.jsonField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="register", WrapperNamespace="http://Services/", IsWrapped=true)]
public partial class registerRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public user arg0;
    
    public registerRequest()
    {
    }
    
    public registerRequest(user arg0)
    {
        this.arg0 = arg0;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="registerResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
public partial class registerResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public response @return;
    
    public registerResponse()
    {
    }
    
    public registerResponse(response @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="moveFile", WrapperNamespace="http://Services/", IsWrapped=true)]
public partial class moveFileRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0;
    
    public moveFileRequest()
    {
    }
    
    public moveFileRequest(string arg0)
    {
        this.arg0 = arg0;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="moveFileResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
public partial class moveFileResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public response @return;
    
    public moveFileResponse()
    {
    }
    
    public moveFileResponse(response @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="deleteFolder", WrapperNamespace="http://Services/", IsWrapped=true)]
public partial class deleteFolderRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public folder arg0;
    
    public deleteFolderRequest()
    {
    }
    
    public deleteFolderRequest(folder arg0)
    {
        this.arg0 = arg0;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="deleteFolderResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
public partial class deleteFolderResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public response @return;
    
    public deleteFolderResponse()
    {
    }
    
    public deleteFolderResponse(response @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="uploadFile", WrapperNamespace="http://Services/", IsWrapped=true)]
public partial class uploadFileRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public file arg0;
    
    public uploadFileRequest()
    {
    }
    
    public uploadFileRequest(file arg0)
    {
        this.arg0 = arg0;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="uploadFileResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
public partial class uploadFileResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public response @return;
    
    public uploadFileResponse()
    {
    }
    
    public uploadFileResponse(response @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="deleteFile", WrapperNamespace="http://Services/", IsWrapped=true)]
public partial class deleteFileRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public file arg0;
    
    public deleteFileRequest()
    {
    }
    
    public deleteFileRequest(file arg0)
    {
        this.arg0 = arg0;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="deleteFileResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
public partial class deleteFileResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public response @return;
    
    public deleteFileResponse()
    {
    }
    
    public deleteFileResponse(response @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="seeStorageTree", WrapperNamespace="http://Services/", IsWrapped=true)]
public partial class seeStorageTreeRequest
{
    
    public seeStorageTreeRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="seeStorageTreeResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
public partial class seeStorageTreeResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public response @return;
    
    public seeStorageTreeResponse()
    {
    }
    
    public seeStorageTreeResponse(response @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="downloadFile", WrapperNamespace="http://Services/", IsWrapped=true)]
public partial class downloadFileRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public file arg0;
    
    public downloadFileRequest()
    {
    }
    
    public downloadFileRequest(file arg0)
    {
        this.arg0 = arg0;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="downloadFileResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
public partial class downloadFileResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public response @return;
    
    public downloadFileResponse()
    {
    }
    
    public downloadFileResponse(response @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="shareFile", WrapperNamespace="http://Services/", IsWrapped=true)]
public partial class shareFileRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int arg0;
    
    public shareFileRequest()
    {
    }
    
    public shareFileRequest(int arg0)
    {
        this.arg0 = arg0;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="shareFileResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
public partial class shareFileResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public response @return;
    
    public shareFileResponse()
    {
    }
    
    public shareFileResponse(response @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="stopSharingFile", WrapperNamespace="http://Services/", IsWrapped=true)]
public partial class stopSharingFileRequest
{
    
    public stopSharingFileRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="stopSharingFileResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
public partial class stopSharingFileResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public response @return;
    
    public stopSharingFileResponse()
    {
    }
    
    public stopSharingFileResponse(response @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="login", WrapperNamespace="http://Services/", IsWrapped=true)]
public partial class loginRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public user arg0;
    
    public loginRequest()
    {
    }
    
    public loginRequest(user arg0)
    {
        this.arg0 = arg0;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="loginResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
public partial class loginResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public response @return;
    
    public loginResponse()
    {
    }
    
    public loginResponse(response @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="createFolder", WrapperNamespace="http://Services/", IsWrapped=true)]
public partial class createFolderRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public folder arg0;
    
    public createFolderRequest()
    {
    }
    
    public createFolderRequest(folder arg0)
    {
        this.arg0 = arg0;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="createFolderResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
public partial class createFolderResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public response @return;
    
    public createFolderResponse()
    {
    }
    
    public createFolderResponse(response @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="verifySession", WrapperNamespace="http://Services/", IsWrapped=true)]
public partial class verifySessionRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0;
    
    public verifySessionRequest()
    {
    }
    
    public verifySessionRequest(string arg0)
    {
        this.arg0 = arg0;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="verifySessionResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
public partial class verifySessionResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public response @return;
    
    public verifySessionResponse()
    {
    }
    
    public verifySessionResponse(response @return)
    {
        this.@return = @return;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ServiceChannel : Service, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServiceClient : System.ServiceModel.ClientBase<Service>, Service
{
    
    public ServiceClient()
    {
    }
    
    public ServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    registerResponse Service.register(registerRequest request)
    {
        return base.Channel.register(request);
    }
    
    public response register(user arg0)
    {
        registerRequest inValue = new registerRequest();
        inValue.arg0 = arg0;
        registerResponse retVal = ((Service)(this)).register(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<registerResponse> Service.registerAsync(registerRequest request)
    {
        return base.Channel.registerAsync(request);
    }
    
    public System.Threading.Tasks.Task<registerResponse> registerAsync(user arg0)
    {
        registerRequest inValue = new registerRequest();
        inValue.arg0 = arg0;
        return ((Service)(this)).registerAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    moveFileResponse Service.moveFile(moveFileRequest request)
    {
        return base.Channel.moveFile(request);
    }
    
    public response moveFile(string arg0)
    {
        moveFileRequest inValue = new moveFileRequest();
        inValue.arg0 = arg0;
        moveFileResponse retVal = ((Service)(this)).moveFile(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<moveFileResponse> Service.moveFileAsync(moveFileRequest request)
    {
        return base.Channel.moveFileAsync(request);
    }
    
    public System.Threading.Tasks.Task<moveFileResponse> moveFileAsync(string arg0)
    {
        moveFileRequest inValue = new moveFileRequest();
        inValue.arg0 = arg0;
        return ((Service)(this)).moveFileAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    deleteFolderResponse Service.deleteFolder(deleteFolderRequest request)
    {
        return base.Channel.deleteFolder(request);
    }
    
    public response deleteFolder(folder arg0)
    {
        deleteFolderRequest inValue = new deleteFolderRequest();
        inValue.arg0 = arg0;
        deleteFolderResponse retVal = ((Service)(this)).deleteFolder(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<deleteFolderResponse> Service.deleteFolderAsync(deleteFolderRequest request)
    {
        return base.Channel.deleteFolderAsync(request);
    }
    
    public System.Threading.Tasks.Task<deleteFolderResponse> deleteFolderAsync(folder arg0)
    {
        deleteFolderRequest inValue = new deleteFolderRequest();
        inValue.arg0 = arg0;
        return ((Service)(this)).deleteFolderAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    uploadFileResponse Service.uploadFile(uploadFileRequest request)
    {
        return base.Channel.uploadFile(request);
    }
    
    public response uploadFile(file arg0)
    {
        uploadFileRequest inValue = new uploadFileRequest();
        inValue.arg0 = arg0;
        uploadFileResponse retVal = ((Service)(this)).uploadFile(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<uploadFileResponse> Service.uploadFileAsync(uploadFileRequest request)
    {
        return base.Channel.uploadFileAsync(request);
    }
    
    public System.Threading.Tasks.Task<uploadFileResponse> uploadFileAsync(file arg0)
    {
        uploadFileRequest inValue = new uploadFileRequest();
        inValue.arg0 = arg0;
        return ((Service)(this)).uploadFileAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    deleteFileResponse Service.deleteFile(deleteFileRequest request)
    {
        return base.Channel.deleteFile(request);
    }
    
    public response deleteFile(file arg0)
    {
        deleteFileRequest inValue = new deleteFileRequest();
        inValue.arg0 = arg0;
        deleteFileResponse retVal = ((Service)(this)).deleteFile(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<deleteFileResponse> Service.deleteFileAsync(deleteFileRequest request)
    {
        return base.Channel.deleteFileAsync(request);
    }
    
    public System.Threading.Tasks.Task<deleteFileResponse> deleteFileAsync(file arg0)
    {
        deleteFileRequest inValue = new deleteFileRequest();
        inValue.arg0 = arg0;
        return ((Service)(this)).deleteFileAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    seeStorageTreeResponse Service.seeStorageTree(seeStorageTreeRequest request)
    {
        return base.Channel.seeStorageTree(request);
    }
    
    public response seeStorageTree()
    {
        seeStorageTreeRequest inValue = new seeStorageTreeRequest();
        seeStorageTreeResponse retVal = ((Service)(this)).seeStorageTree(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<seeStorageTreeResponse> Service.seeStorageTreeAsync(seeStorageTreeRequest request)
    {
        return base.Channel.seeStorageTreeAsync(request);
    }
    
    public System.Threading.Tasks.Task<seeStorageTreeResponse> seeStorageTreeAsync()
    {
        seeStorageTreeRequest inValue = new seeStorageTreeRequest();
        return ((Service)(this)).seeStorageTreeAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    downloadFileResponse Service.downloadFile(downloadFileRequest request)
    {
        return base.Channel.downloadFile(request);
    }
    
    public response downloadFile(file arg0)
    {
        downloadFileRequest inValue = new downloadFileRequest();
        inValue.arg0 = arg0;
        downloadFileResponse retVal = ((Service)(this)).downloadFile(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<downloadFileResponse> Service.downloadFileAsync(downloadFileRequest request)
    {
        return base.Channel.downloadFileAsync(request);
    }
    
    public System.Threading.Tasks.Task<downloadFileResponse> downloadFileAsync(file arg0)
    {
        downloadFileRequest inValue = new downloadFileRequest();
        inValue.arg0 = arg0;
        return ((Service)(this)).downloadFileAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    shareFileResponse Service.shareFile(shareFileRequest request)
    {
        return base.Channel.shareFile(request);
    }
    
    public response shareFile(int arg0)
    {
        shareFileRequest inValue = new shareFileRequest();
        inValue.arg0 = arg0;
        shareFileResponse retVal = ((Service)(this)).shareFile(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<shareFileResponse> Service.shareFileAsync(shareFileRequest request)
    {
        return base.Channel.shareFileAsync(request);
    }
    
    public System.Threading.Tasks.Task<shareFileResponse> shareFileAsync(int arg0)
    {
        shareFileRequest inValue = new shareFileRequest();
        inValue.arg0 = arg0;
        return ((Service)(this)).shareFileAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    stopSharingFileResponse Service.stopSharingFile(stopSharingFileRequest request)
    {
        return base.Channel.stopSharingFile(request);
    }
    
    public response stopSharingFile()
    {
        stopSharingFileRequest inValue = new stopSharingFileRequest();
        stopSharingFileResponse retVal = ((Service)(this)).stopSharingFile(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<stopSharingFileResponse> Service.stopSharingFileAsync(stopSharingFileRequest request)
    {
        return base.Channel.stopSharingFileAsync(request);
    }
    
    public System.Threading.Tasks.Task<stopSharingFileResponse> stopSharingFileAsync()
    {
        stopSharingFileRequest inValue = new stopSharingFileRequest();
        return ((Service)(this)).stopSharingFileAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    loginResponse Service.login(loginRequest request)
    {
        return base.Channel.login(request);
    }
    
    public response login(user arg0)
    {
        loginRequest inValue = new loginRequest();
        inValue.arg0 = arg0;
        loginResponse retVal = ((Service)(this)).login(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<loginResponse> Service.loginAsync(loginRequest request)
    {
        return base.Channel.loginAsync(request);
    }
    
    public System.Threading.Tasks.Task<loginResponse> loginAsync(user arg0)
    {
        loginRequest inValue = new loginRequest();
        inValue.arg0 = arg0;
        return ((Service)(this)).loginAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    createFolderResponse Service.createFolder(createFolderRequest request)
    {
        return base.Channel.createFolder(request);
    }
    
    public response createFolder(folder arg0)
    {
        createFolderRequest inValue = new createFolderRequest();
        inValue.arg0 = arg0;
        createFolderResponse retVal = ((Service)(this)).createFolder(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<createFolderResponse> Service.createFolderAsync(createFolderRequest request)
    {
        return base.Channel.createFolderAsync(request);
    }
    
    public System.Threading.Tasks.Task<createFolderResponse> createFolderAsync(folder arg0)
    {
        createFolderRequest inValue = new createFolderRequest();
        inValue.arg0 = arg0;
        return ((Service)(this)).createFolderAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    verifySessionResponse Service.verifySession(verifySessionRequest request)
    {
        return base.Channel.verifySession(request);
    }
    
    public response verifySession(string arg0)
    {
        verifySessionRequest inValue = new verifySessionRequest();
        inValue.arg0 = arg0;
        verifySessionResponse retVal = ((Service)(this)).verifySession(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<verifySessionResponse> Service.verifySessionAsync(verifySessionRequest request)
    {
        return base.Channel.verifySessionAsync(request);
    }
    
    public System.Threading.Tasks.Task<verifySessionResponse> verifySessionAsync(string arg0)
    {
        verifySessionRequest inValue = new verifySessionRequest();
        inValue.arg0 = arg0;
        return ((Service)(this)).verifySessionAsync(inValue);
    }
}
