//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Services/", ConfigurationName="ServiceReference1.Service")]
    public interface Service
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/registerRequest", ReplyAction="http://Services/Service/registerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.registerResponse> registerAsync(ServiceReference1.registerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/moveFileRequest", ReplyAction="http://Services/Service/moveFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.moveFileResponse> moveFileAsync(ServiceReference1.moveFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/deleteFolderRequest", ReplyAction="http://Services/Service/deleteFolderResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.deleteFolderResponse> deleteFolderAsync(ServiceReference1.deleteFolderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/uploadFileRequest", ReplyAction="http://Services/Service/uploadFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.uploadFileResponse> uploadFileAsync(ServiceReference1.uploadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/deleteFileRequest", ReplyAction="http://Services/Service/deleteFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.deleteFileResponse> deleteFileAsync(ServiceReference1.deleteFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/seeStorageTreeRequest", ReplyAction="http://Services/Service/seeStorageTreeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.seeStorageTreeResponse> seeStorageTreeAsync(ServiceReference1.seeStorageTreeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/downloadFileRequest", ReplyAction="http://Services/Service/downloadFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.downloadFileResponse> downloadFileAsync(ServiceReference1.downloadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/shareFileRequest", ReplyAction="http://Services/Service/shareFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.shareFileResponse> shareFileAsync(ServiceReference1.shareFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/stopSharingFileRequest", ReplyAction="http://Services/Service/stopSharingFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.stopSharingFileResponse> stopSharingFileAsync(ServiceReference1.stopSharingFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/loginRequest", ReplyAction="http://Services/Service/loginResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.loginResponse> loginAsync(ServiceReference1.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/createFolderRequest", ReplyAction="http://Services/Service/createFolderResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.createFolderResponse> createFolderAsync(ServiceReference1.createFolderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/Service/verifySessionRequest", ReplyAction="http://Services/Service/verifySessionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.verifySessionResponse> verifySessionAsync(ServiceReference1.verifySessionRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services/")]
    public partial class user
    {
        
        private int idField;
        
        private string nameField;
        
        private string surnameField;
        
        private string emailField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string surname
        {
            get
            {
                return this.surnameField;
            }
            set
            {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services/")]
    public partial class file
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services/")]
    public partial class folder
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services/")]
    public partial class response
    {
        
        private int statusCodeField;
        
        private string detailsField;
        
        private string jsonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int statusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string json
        {
            get
            {
                return this.jsonField;
            }
            set
            {
                this.jsonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="register", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class registerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.user arg0;
        
        public registerRequest()
        {
        }
        
        public registerRequest(ServiceReference1.user arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class registerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.response @return;
        
        public registerResponse()
        {
        }
        
        public registerResponse(ServiceReference1.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="moveFile", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class moveFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public moveFileRequest()
        {
        }
        
        public moveFileRequest(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="moveFileResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class moveFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.response @return;
        
        public moveFileResponse()
        {
        }
        
        public moveFileResponse(ServiceReference1.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteFolder", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class deleteFolderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.folder arg0;
        
        public deleteFolderRequest()
        {
        }
        
        public deleteFolderRequest(ServiceReference1.folder arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteFolderResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class deleteFolderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.response @return;
        
        public deleteFolderResponse()
        {
        }
        
        public deleteFolderResponse(ServiceReference1.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="uploadFile", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class uploadFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.file arg0;
        
        public uploadFileRequest()
        {
        }
        
        public uploadFileRequest(ServiceReference1.file arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="uploadFileResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class uploadFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.response @return;
        
        public uploadFileResponse()
        {
        }
        
        public uploadFileResponse(ServiceReference1.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteFile", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class deleteFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.file arg0;
        
        public deleteFileRequest()
        {
        }
        
        public deleteFileRequest(ServiceReference1.file arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteFileResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class deleteFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.response @return;
        
        public deleteFileResponse()
        {
        }
        
        public deleteFileResponse(ServiceReference1.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="seeStorageTree", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class seeStorageTreeRequest
    {
        
        public seeStorageTreeRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="seeStorageTreeResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class seeStorageTreeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.response @return;
        
        public seeStorageTreeResponse()
        {
        }
        
        public seeStorageTreeResponse(ServiceReference1.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="downloadFile", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class downloadFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.file arg0;
        
        public downloadFileRequest()
        {
        }
        
        public downloadFileRequest(ServiceReference1.file arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="downloadFileResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class downloadFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.response @return;
        
        public downloadFileResponse()
        {
        }
        
        public downloadFileResponse(ServiceReference1.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="shareFile", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class shareFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public shareFileRequest()
        {
        }
        
        public shareFileRequest(int arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="shareFileResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class shareFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.response @return;
        
        public shareFileResponse()
        {
        }
        
        public shareFileResponse(ServiceReference1.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="stopSharingFile", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class stopSharingFileRequest
    {
        
        public stopSharingFileRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="stopSharingFileResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class stopSharingFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.response @return;
        
        public stopSharingFileResponse()
        {
        }
        
        public stopSharingFileResponse(ServiceReference1.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="login", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class loginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.user arg0;
        
        public loginRequest()
        {
        }
        
        public loginRequest(ServiceReference1.user arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class loginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.response @return;
        
        public loginResponse()
        {
        }
        
        public loginResponse(ServiceReference1.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createFolder", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class createFolderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.folder arg0;
        
        public createFolderRequest()
        {
        }
        
        public createFolderRequest(ServiceReference1.folder arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createFolderResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class createFolderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.response @return;
        
        public createFolderResponse()
        {
        }
        
        public createFolderResponse(ServiceReference1.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verifySession", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class verifySessionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public verifySessionRequest()
        {
        }
        
        public verifySessionRequest(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verifySessionResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class verifySessionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.response @return;
        
        public verifySessionResponse()
        {
        }
        
        public verifySessionResponse(ServiceReference1.response @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ServiceChannel : ServiceReference1.Service, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<ServiceReference1.Service>, ServiceReference1.Service
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceClient() : 
                base(ServiceClient.GetDefaultBinding(), ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.registerResponse> ServiceReference1.Service.registerAsync(ServiceReference1.registerRequest request)
        {
            return base.Channel.registerAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.registerResponse> registerAsync(ServiceReference1.user arg0)
        {
            ServiceReference1.registerRequest inValue = new ServiceReference1.registerRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference1.Service)(this)).registerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.moveFileResponse> ServiceReference1.Service.moveFileAsync(ServiceReference1.moveFileRequest request)
        {
            return base.Channel.moveFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.moveFileResponse> moveFileAsync(string arg0)
        {
            ServiceReference1.moveFileRequest inValue = new ServiceReference1.moveFileRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference1.Service)(this)).moveFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.deleteFolderResponse> ServiceReference1.Service.deleteFolderAsync(ServiceReference1.deleteFolderRequest request)
        {
            return base.Channel.deleteFolderAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.deleteFolderResponse> deleteFolderAsync(ServiceReference1.folder arg0)
        {
            ServiceReference1.deleteFolderRequest inValue = new ServiceReference1.deleteFolderRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference1.Service)(this)).deleteFolderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.uploadFileResponse> ServiceReference1.Service.uploadFileAsync(ServiceReference1.uploadFileRequest request)
        {
            return base.Channel.uploadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.uploadFileResponse> uploadFileAsync(ServiceReference1.file arg0)
        {
            ServiceReference1.uploadFileRequest inValue = new ServiceReference1.uploadFileRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference1.Service)(this)).uploadFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.deleteFileResponse> ServiceReference1.Service.deleteFileAsync(ServiceReference1.deleteFileRequest request)
        {
            return base.Channel.deleteFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.deleteFileResponse> deleteFileAsync(ServiceReference1.file arg0)
        {
            ServiceReference1.deleteFileRequest inValue = new ServiceReference1.deleteFileRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference1.Service)(this)).deleteFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.seeStorageTreeResponse> ServiceReference1.Service.seeStorageTreeAsync(ServiceReference1.seeStorageTreeRequest request)
        {
            return base.Channel.seeStorageTreeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.seeStorageTreeResponse> seeStorageTreeAsync()
        {
            ServiceReference1.seeStorageTreeRequest inValue = new ServiceReference1.seeStorageTreeRequest();
            return ((ServiceReference1.Service)(this)).seeStorageTreeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.downloadFileResponse> ServiceReference1.Service.downloadFileAsync(ServiceReference1.downloadFileRequest request)
        {
            return base.Channel.downloadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.downloadFileResponse> downloadFileAsync(ServiceReference1.file arg0)
        {
            ServiceReference1.downloadFileRequest inValue = new ServiceReference1.downloadFileRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference1.Service)(this)).downloadFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.shareFileResponse> ServiceReference1.Service.shareFileAsync(ServiceReference1.shareFileRequest request)
        {
            return base.Channel.shareFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.shareFileResponse> shareFileAsync(int arg0)
        {
            ServiceReference1.shareFileRequest inValue = new ServiceReference1.shareFileRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference1.Service)(this)).shareFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.stopSharingFileResponse> ServiceReference1.Service.stopSharingFileAsync(ServiceReference1.stopSharingFileRequest request)
        {
            return base.Channel.stopSharingFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.stopSharingFileResponse> stopSharingFileAsync()
        {
            ServiceReference1.stopSharingFileRequest inValue = new ServiceReference1.stopSharingFileRequest();
            return ((ServiceReference1.Service)(this)).stopSharingFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.loginResponse> ServiceReference1.Service.loginAsync(ServiceReference1.loginRequest request)
        {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.loginResponse> loginAsync(string email, ServiceReference1.user arg0)
        {
            ServiceReference1.loginRequest inValue = new ServiceReference1.loginRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference1.Service)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.createFolderResponse> ServiceReference1.Service.createFolderAsync(ServiceReference1.createFolderRequest request)
        {
            return base.Channel.createFolderAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.createFolderResponse> createFolderAsync(ServiceReference1.folder arg0)
        {
            ServiceReference1.createFolderRequest inValue = new ServiceReference1.createFolderRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference1.Service)(this)).createFolderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.verifySessionResponse> ServiceReference1.Service.verifySessionAsync(ServiceReference1.verifySessionRequest request)
        {
            return base.Channel.verifySessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.verifySessionResponse> verifySessionAsync(string arg0)
        {
            ServiceReference1.verifySessionRequest inValue = new ServiceReference1.verifySessionRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference1.Service)(this)).verifySessionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:1802/app");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceClient.GetBindingForEndpoint(EndpointConfiguration.ServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceClient.GetEndpointAddress(EndpointConfiguration.ServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            ServicePort,
        }
    }
}
